[workspace]
resolver = "2"
members = [
    "vir",
    "vir-lsp",
    "vir-dump",
    "vir-compile",
    "virdant",
    "virdant-tokenizer",
    "virdant-parser",
    "virdant-common",
    "virdant-hir",
]
