pub mod check;
pub mod check_drivers;
pub mod component;
pub mod location;
pub mod package;
pub mod parsing;
pub mod syntax;
pub mod typecheck;
pub mod types;
pub mod typing;

pub(crate) use check::check;
pub(crate) use check_drivers::check_drivers;
pub(crate) use component::build_component_analysis;
pub(crate) use location::build_location_region;
pub(crate) use package::build_package_analysis;
pub(crate) use parsing::build_parsing;
pub(crate) use syntax::{build_all_exprs, find_exprroots, build_syntax_errors};
pub(crate) use typecheck::{build_typeof, build_typeof_all};
pub(crate) use types::{build_type_monomorphizations, build_typedefs};
pub(crate) use typing::{build_expected_type, build_typing, build_typing_context};
