name: Run cargo test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Rustc version
      run: |
        rustup update
        rustup toolchain install 1.88.0
        rustup default 1.88.0

    - name: Install Verilator
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator

    - name: Run tests
      run: make test
