//! Code generator for creating the db.rs file from scanned functions

use crate::scanner::QueryFunction;
use quote::{quote, format_ident};
use proc_macro2::{TokenStream, Ident};
use std::str::FromStr;

/// Generate the complete database module
pub fn generate_database(
    functions: &[QueryFunction],
    config: &crate::Configuration,
) -> anyhow::Result<String> {
    // Extract configurations
    let db_name = format_ident!("{}", config.db_name);
    let builder_name = format_ident!("{}", config.builder_name);
    let query_enum_name = format_ident!("{}", config.query_enum_name);

    // Separate inputs and queries
    let inputs: Vec<_> = functions.iter().filter(|f| f.is_input).collect();
    let queries: Vec<_> = functions.iter().filter(|f| !f.is_input).collect();

    // Generate components
    let query_enum = generate_query_enum(&query_enum_name, functions);
    let query_result_enum = generate_query_result_enum(&format_ident!("QueryResult"), functions);
    let is_input_impl = generate_is_input_impl(&query_enum_name, &inputs);
    let build_impl = generate_build_impl(&query_enum_name, &builder_name, &db_name, &queries);
    let db_accessor_methods = generate_db_accessor_methods(&query_enum_name, functions);
    let builder_accessor_methods = generate_builder_accessor_methods(&query_enum_name, functions);
    let setter_methods = generate_setter_methods(&db_name, &query_enum_name, &inputs);

    // Combine everything
    let tokens = quote! {
        // THIS FILE IS AUTOMATICALLY GENERATED BY virdant-db
        // DO NOT EDIT MANUALLY

        use virdant_db::runtime::{Db as DbImpl, Builder as BuilderImpl, CachedVal, QueryTrait, QueryResultTrait};

        #query_enum

        #query_result_enum

        impl QueryTrait for #query_enum_name {
            #is_input_impl
        }

        impl QueryResultTrait for QueryResult {}

        /// The main database struct for incremental computation
        pub struct #db_name {
            inner: DbImpl<#query_enum_name, QueryResult>,
        }

        impl #db_name {
            pub fn new() -> Self {
                Self {
                    inner: DbImpl::new(),
                }
            }

            /// Get or build a query result with caching and dependency tracking
            #[track_caller]
            fn get_or_build(&self, query: #query_enum_name, location: std::panic::Location<'static>) -> CachedVal<#query_enum_name, QueryResult> {
                // Check if we have a cached value that's still valid
                // We need to check this while holding all necessary locks to avoid deadlock
                let needs_rebuild = {
                    let map = self.inner.map.lock().unwrap();
                    if let Some(cached) = map.get(&query) {
                        // Check if cached value is dirty
                        let mut dirty_cache = self.inner.dirty_cache.lock().unwrap();
                        let is_dirty = DbImpl::<#query_enum_name, QueryResult>::is_dirty_internal(
                            &query,
                            cached,
                            &map,
                            &mut dirty_cache,
                            self.inner.rev,
                        );
                        if !is_dirty {
                            return cached.clone();
                        }
                        true
                    } else {
                        true
                    }
                };

                if needs_rebuild {
                    // Check for cycles
                    {
                        let mut stack = self.inner.call_stack.lock().unwrap();
                        if stack.contains(&query) {
                            eprintln!("Cycle detected at {location}");
                            self.inner.dump_call_stack();
                            panic!("Query cycle detected: {:?}", query);
                        }
                        stack.push(query.clone());
                    }

                    // Build the query
                    let cached_val = query.build(self);

                    // Pop from call stack
                    self.inner.call_stack.lock().unwrap().pop();

                    // Store in cache
                    self.inner.map.lock().unwrap().insert(query.clone(), cached_val.clone());

                    cached_val
                } else {
                    unreachable!("Should have returned cached value above")
                }
            }

            #db_accessor_methods
            #setter_methods
        }

        /// Builder for tracking dependencies during query execution
        pub struct #builder_name <'d> {
            db: &'d #db_name,
            deps: IndexSet<#query_enum_name>,
        }

        impl<'d> #builder_name <'d> {
            fn new(db: &'d #db_name) -> Self {
                Self {
                    db,
                    deps: IndexSet::new(),
                }
            }

            #builder_accessor_methods
        }

        impl #query_enum_name {
            #build_impl
        }
    };

    // Format with rustfmt if available
    format_tokens(tokens)
}

/// Generate the Query enum
fn generate_query_enum(name: &Ident, functions: &[QueryFunction]) -> TokenStream {
    let variants = functions.iter().map(|func| {
        let variant_name = format_ident!("{}", capitalize(&func.name));
        let params = func.params.iter().map(|p| {
            let ty = TokenStream::from_str(&p.ty).unwrap_or_else(|_| quote! { UnknownType });
            quote! { #ty }
        });

        if func.params.is_empty() {
            quote! { #variant_name() }
        } else {
            quote! { #variant_name(#(#params),*) }
        }
    });

    quote! {
        #[derive(Clone, Debug, PartialEq, Eq, Hash)]
        pub enum #name {
            #(#variants,)*
        }
    }
}

/// Generate the QueryResult enum
fn generate_query_result_enum(name: &Ident, functions: &[QueryFunction]) -> TokenStream {
    let variants = functions.iter().map(|func| {
        let variant_name = format_ident!("{}", capitalize(&func.name));
        let ret_ty = TokenStream::from_str(&func.return_type)
            .unwrap_or_else(|_| quote! { UnknownType });
        quote! { #variant_name(#ret_ty) }
    });

    quote! {
        #[derive(Clone, Debug)]
        pub enum #name {
            #(#variants,)*
        }
    }
}

/// Generate the is_input() implementation
fn generate_is_input_impl(enum_name: &Ident, inputs: &[&QueryFunction]) -> TokenStream {
    let patterns = inputs.iter().map(|input| {
        let variant = format_ident!("{}", capitalize(&input.name));
        quote! { #enum_name::#variant(..) }
    });

    quote! {
        fn is_input(&self) -> bool {
            matches!(self, #(#patterns)|*)
        }
    }
}

/// Generate the build() method implementation
fn generate_build_impl(
    enum_name: &Ident,
    builder_name: &Ident,
    db_name: &Ident,
    queries: &[&QueryFunction],
) -> TokenStream {
    let arms = queries.iter().map(|query| {
        let variant = format_ident!("{}", capitalize(&query.name));
        let var_names: Vec<_> = query.params.iter()
            .enumerate()
            .map(|(i, _)| format_ident!("arg{}", i))
            .collect();

        let pattern = if var_names.is_empty() {
            quote! { #enum_name::#variant() }
        } else {
            quote! { #enum_name::#variant(#(#var_names),*) }
        };

        // Parse the path to the build function
        let build_fn = TokenStream::from_str(&query.path)
            .unwrap_or_else(|_| quote! { unimplemented });

        quote! {
            #pattern => {
                let mut builder = #builder_name::new(db);
                let result = #build_fn(&mut builder #(, #var_names.clone())*);
                CachedVal {
                    val: QueryResult::#variant(result),
                    rev: db.inner.rev,
                    deps: builder.deps.into_iter().collect(),
                    duration: std::time::Duration::ZERO,
                }
            }
        }
    });
    if !queries.is_empty() {
        quote! {
            fn build(&self, db: &#db_name) -> CachedVal<Self, QueryResult> {
                if self.is_input() {
                    panic!("Cannot build input query");
                }

                match self {
                    #(#arms)*
                    _ => unreachable!("All non-input cases should be handled"),
                }
            }
        }
    } else {
        quote! {
            fn build(&self, db: &#db_name) -> CachedVal<Self, QueryResult> {
                panic!("No queries to build");
            }
        }
    }
}

/// Generate accessor methods for Db
fn generate_db_accessor_methods(
    query_enum: &Ident,
    functions: &[QueryFunction],
) -> TokenStream {
    let methods = functions.iter().map(|func| {
        let method_name = format_ident!("{}", func.method_name);
        let variant = format_ident!("{}", capitalize(&func.name));

        let params = func.params.iter().map(|p| {
            let name = format_ident!("{}", p.name);
            let ty = TokenStream::from_str(&p.ty)
                .unwrap_or_else(|_| quote! { UnknownType });
            quote! { #name: #ty }
        });

        let args = func.params.iter().map(|p| {
            let name = format_ident!("{}", p.name);
            quote! { #name }
        });

        let ret_ty = TokenStream::from_str(&func.return_type)
            .unwrap_or_else(|_| quote! { UnknownType });

        quote! {
            #[track_caller]
            pub fn #method_name(&self, #(#params),*) -> #ret_ty {
                let query = #query_enum::#variant(#(#args),*);
                let cached_val = self.get_or_build(query, *std::panic::Location::caller());
                match cached_val.val {
                    QueryResult::#variant(v) => v,
                    _ => unreachable!("Type mismatch"),
                }
            }
        }
    });

    quote! { #(#methods)* }
}

/// Generate accessor methods for Builder
fn generate_builder_accessor_methods(
    query_enum: &Ident,
    functions: &[QueryFunction],
) -> TokenStream {
    let methods = functions.iter().map(|func| {
        let method_name = format_ident!("{}", func.method_name);
        let variant = format_ident!("{}", capitalize(&func.name));

        let params = func.params.iter().map(|p| {
            let name = format_ident!("{}", p.name);
            let ty = TokenStream::from_str(&p.ty)
                .unwrap_or_else(|_| quote! { UnknownType });
            quote! { #name: #ty }
        });

        let args = func.params.iter().map(|p| {
            let name = format_ident!("{}", p.name);
            quote! { #name }
        });

        let ret_ty = TokenStream::from_str(&func.return_type)
            .unwrap_or_else(|_| quote! { UnknownType });

        quote! {
            #[track_caller]
            pub fn #method_name(&mut self, #(#params),*) -> #ret_ty {
                let query = #query_enum::#variant(#(#args),*);
                self.deps.insert(query.clone());
                let cached_val = self.db.get_or_build(query, *std::panic::Location::caller());
                match cached_val.val {
                    QueryResult::#variant(v) => v,
                    _ => unreachable!("Type mismatch"),
                }
            }
        }
    });

    quote! { #(#methods)* }
}

/// Generate setter methods for inputs
fn generate_setter_methods(
    _db_name: &Ident,
    query_enum: &Ident,
    inputs: &[&QueryFunction],
) -> TokenStream {
    let methods = inputs.iter().map(|input| {
        let setter_name = format_ident!("{}", input.setter_name);
        let variant = format_ident!("{}", capitalize(&input.name));

        let params = input.params.iter().map(|p| {
            let name = format_ident!("{}", p.name);
            let ty = TokenStream::from_str(&p.ty)
                .unwrap_or_else(|_| quote! { UnknownType });
            quote! { #name: #ty }
        });

        let args = input.params.iter().map(|p| {
            let name = format_ident!("{}", p.name);
            quote! { #name }
        });

        let value_ty = TokenStream::from_str(&input.return_type)
            .unwrap_or_else(|_| quote! { UnknownType });

        quote! {
            pub fn #setter_name(&mut self, #(#params,)* value: #value_ty) {
                self.inner.increment_revision();
                let query = #query_enum::#variant(#(#args),*);
                let cached_val = CachedVal {
                    val: QueryResult::#variant(value),
                    rev: self.inner.rev,
                    deps: vec![],
                    duration: std::time::Duration::ZERO,
                };
                self.inner.set_value(query, cached_val);
            }
        }
    });

    quote! { #(#methods)* }
}

/// Capitalize the first letter of a string
fn capitalize(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_uppercase().chain(c).collect(),
    }
}

/// Format the generated tokens as a string
fn format_tokens(tokens: TokenStream) -> anyhow::Result<String> {
    let code = tokens.to_string();

    // Try to format with rustfmt if available
    // For now, just return the raw tokens
    Ok(code)
}
